version: '3.7'

services:
  web:
    image: meroxbe/erasmail_web:test
    build:
      context: ./back-end/erasmail
    command: gunicorn erasmail.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: meroxbe/postgres:test
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: meroxbe/erasmail_nginx:test
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data: